add builder
ausaccessfed/publish_app pull request #9
Opened 2023-01-09 01:51 UTC by phyzical

2023-01-09 07:32 UTC, matthew-puku requested changes

2023-01-09 07:32 UTC, matthew-puku commented on Makefile
> +	docker run ${DOCKER_ECR}publish_app discovery-service asd asd test,production
maybe something not `asd asd` would be more informative

2023-01-09 07:32 UTC, matthew-puku commented on .gitignore
> +.env
nit: newline, editorconfig

2023-01-09 07:32 UTC, matthew-puku commented on .github/workflows/build.yml
> +      group: ${{ github.event_name }}-${{ github.ref_name == 'master' && github.sha || github.ref_name }}-build
main?

2023-01-09 07:32 UTC, matthew-puku commented on .github/workflows/build.yml
> +      group: ${{ github.event_name }}-${{ github.ref_name == 'master' && github.sha || github.ref_name }}-build
also elsewhere

2023-01-10 01:10 UTC, phyzical commented on .github/workflows/build.yml
> +        if: github.event_name == 'push' && github.ref_name == 'master'
```suggestion
        if: github.event_name == 'push' && github.ref_name == 'main'
```

2023-01-10 01:11 UTC, phyzical commented on .gitignore
> +.env
```suggestion
.env

```

2023-01-10 01:11 UTC, phyzical commented on Makefile
> +	docker run ${DOCKER_ECR}publish_app discovery-service asd asd test,production
ah its redundant anyway was testing a way to get it working

2023-01-10 01:12 UTC, phyzical commented on Makefile
> +	docker run ${DOCKER_ECR}publish_app discovery-service asd asd test,production
```suggestion
```

2023-01-10 01:13 UTC, phyzical commented on .github/workflows/build.yml
> +      group: ${{ github.event_name }}-${{ github.ref_name == 'master' && github.sha || github.ref_name }}-build
```suggestion
      group: ${{ github.event_name }}-${{ github.ref_name == 'main' && github.sha || github.ref_name }}-build
```

2023-01-10 01:34 UTC, matthew-puku approved these changes

2023-01-10 01:34 UTC, merged